version: '3'

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/conf:/etc/nginx/conf.d
        ports: 
            - "50000:80"
            - "8081:8081"
            - "5001:5001"
        depends_on:
            - management_server
            - task_server
        container_name: nginx
    management_server:
        build:
            dockerfile: ./VolunteerComputing.ManagementServer/Dockerfile
            context: ./
        volumes:
            - ./VolunteerComputing.ManagementServer/Server/appsettings.json:/src/Server/appsettings.json
            - ./VolunteerComputing.ManagementServer/Server/appsettings.json:/app/appsettings.json
            - ./VolunteerComputing.ManagementServer/Server/appsettings.Development.json:/src/Server/appsettings.Development.json
            - ./VolunteerComputing.ManagementServer/Server/appsettings.Development.json:/app/appsettings.Development.json
            - ./Upload:/src/Upload
        #restart: always
        container_name: management_server
        depends_on:
            - database
        links:
            - database:mssql
    task_server:
        build:
            dockerfile: ./VolunteerComputing.TaskServer/Dockerfile
            context: ./
        volumes:
            - ./VolunteerComputing.TaskServer/appsettings.json:/src/Server/appsettings.json
            - ./VolunteerComputing.TaskServer/appsettings.json:/app/appsettings.json
            - ./VolunteerComputing.TaskServer/appsettings.Development.json:/src/Server/appsettings.Development.json
            - ./VolunteerComputing.TaskServer/appsettings.Development.json:/app/appsettings.Development.json
            - ./Upload:/src/Upload
        #restart: always
        container_name: task_server
        depends_on:
            - database
            - management_server
        links:
            - database:mssql
    database:
        image: mcr.microsoft.com/mssql/server 
        user: root
        volumes:
            - ./../db:/var/opt/mssql/
        #restart: always
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: eFPLWKA5xpxo
        container_name: database
