// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using VolunteerComputing.Shared.Models;
using VolunteerComputing.TaskServer;

#nullable disable

namespace VolunteerComputing.TaskServer.Data
{
    public partial class VolunteerComputingContext : DbContext
    {
        public VolunteerComputingContext()
        {
        }

        public VolunteerComputingContext(DbContextOptions<VolunteerComputingContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ComputeTask> ComputeTasks { get; set; }
        public virtual DbSet<Packet> Packets { get; set; }
        public virtual DbSet<PacketType> PacketTypes { get; set; }
        public virtual DbSet<PacketTypeToComputeTask> PacketTypeToComputeTasks { get; set; }
        public virtual DbSet<DeviceData> Devices { get; set; }
        public virtual DbSet<DeviceStat> DeviceStats { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<PacketBundle> Bundles { get; set; }
        public virtual DbSet<BundleResult> BundleResults { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            /*if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\mssqllocaldb;Initial Catalog=VolunteerComputing;Integrated Security=True");
            }*/
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}